// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frjtusbuhxrwksksxgil.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyanR1c2J1aHhyd2tza3N4Z2lsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5Njk0MTgsImV4cCI6MjA2NzU0NTQxOH0.4LTMckz-X-gAFUAEVsYG2CauNDNDGdOE0Em3RF9jx84";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});